CREATE OR REPLACE VIEW vw_miembros_pagos_info AS (
SELECT
    M.ID_MIEMBRO,
    M.NOMBRE_MIEMBRO,
    M.FECHA_ALTA,
    P.TIPO_MEMBRESIA,
    P.FECHA_ULTIMO_PAGO
FROM
    MIEMBROS AS M
    LEFT JOIN PAGOS AS P ON M.ID_MIEMBRO = P.ID_MIEMBRO);

CREATE OR REPLACE VIEW vw_empleados_puestos AS (
SELECT
    E.NOMBRE_EMPLEADO AS EMPLEADO,
    P.DESCRIPCIÓN AS PUESTO
FROM
    EMPLEADOS AS E
    JOIN PUESTOS_EMPLEADOS AS P ON E.ID_PUESTO = P.ID_PUESTO );
    
CREATE OR REPLACE VIEW vw_clases_empleados_hoy AS (
SELECT
    C.NOMBRE_CLASE AS CLASE,
    C.HORARIO,
    E.NOMBRE_EMPLEADO AS INSTRUCTOR
FROM
    CLASES AS C
    LEFT JOIN EMPLEADOS AS E ON C.ID_EMPLEADO = E.ID_EMPLEADO
WHERE
    FIND_IN_SET(DAYNAME(NOW()), C.DIAS) > 0
ORDER BY
    C.HORARIO ASC);

CREATE OR REPLACE VIEW vw_clase_empleado_material AS (
SELECT 
    E.NOMBRE_EMPLEADO AS INSTRUCTOR,
    C.NOMBRE_CLASE AS CLASE,
    M.NOMBRE_MATERIAL AS MATERIAL
FROM
    CLASES AS C
    LEFT JOIN EMPLEADOS AS E ON C.ID_EMPLEADO = E.ID_EMPLEADO
    LEFT JOIN MATERIALES AS M ON C.ID_MATERIAL = M.ID_MATERIAL
ORDER BY
    E.NOMBRE_EMPLEADO ASC
);

CREATE OR REPLACE VIEW vw_materiales_mantenimiento AS (
SELECT
    M.NOMBRE_MATERIAL,
    M.FECHA_MANTENIMIENTO
FROM
    MATERIALES M
WHERE
    M.FECHA_MANTENIMIENTO IS NOT NULL);