-- Proyecto SQL: Gimnasio.
DROP SCHEMA IF EXISTS fitnessclub_db;
CREATE SCHEMA IF NOT EXISTS fitnessclub_db;
USE fitnessclub_db;

-- Tabla MIEMBRO
DROP TABLE IF EXISTS MIEMBROS;
CREATE TABLE `MIEMBROS` (
    `ID_MIEMBRO` INT NOT NULL,
    `NOMBRE_MIEMBRO` VARCHAR(255) NOT NULL,
    `DNI_MIEMBRO` INT NOT NULL,
    `NACIMIENTO` DATE NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `CELULAR` INT NOT NULL,
    `CONTACTO_EMERGENCIA` INT NOT NULL,
    `ACTO_MEDICO` ENUM('SI', 'NO') NOT NULL,
    `FECHA_ALTA` DATE NOT NULL,
    PRIMARY KEY (`ID_MIEMBRO`));
    
-- Tabla PAGOS
DROP TABLE IF EXISTS PAGOS;
CREATE TABLE `PAGOS` (
    `ID_MIEMBRO` INT NOT NULL,
    `TIPO_MEMBRESIA` VARCHAR(255) NOT NULL,
    `MONTO` DECIMAL(10, 2) NOT NULL,
	`FECHA_ULTIMO_PAGO` DATE NOT NULL,
    `METODO_DE_PAGO` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID_MIEMBRO`),
    FOREIGN KEY (`ID_MIEMBRO`) REFERENCES MIEMBROS(`ID_MIEMBRO`)
);

-- Tabla REGISTRO DE PAGOS
DROP TABLE IF EXISTS REGISTRO_PAGOS;
CREATE TABLE `REGISTRO_PAGOS` (
	`ID_PAGO` VARCHAR (50) NOT NULL,
    `ID_MIEMBRO` INT NOT NULL,
    `PERIODO` VARCHAR(50) NOT NULL,
	`FECHA_DE_PAGO` DATETIME NOT NULL,
    PRIMARY KEY (`ID_PAGO`),
    FOREIGN KEY (`ID_MIEMBRO`) REFERENCES MIEMBROS(`ID_MIEMBRO`)
);

-- Tabla MATERIALES
DROP TABLE IF EXISTS MATERIALES;
CREATE TABLE `MATERIALES` (
    `ID_MATERIAL` INT NOT NULL,
    `NOMBRE_MATERIAL` VARCHAR(255) NOT NULL,
    `FECHA_DE_COMPRA` DATE NOT NULL,
    `FECHA_MANTENIMIENTO` DATE,
    PRIMARY KEY (`ID_MATERIAL`)
);

-- Tabla PUESTOS_EMPLEADOS
DROP TABLE IF EXISTS PUESTOS_EMPLEADOS;
CREATE TABLE `PUESTOS_EMPLEADOS` (
    `ID_PUESTO` INT NOT NULL,
    `DESCRIPCIÓN` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID_PUESTO`)
);

-- Tabla EMPLEADOS
DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE `EMPLEADOS` (
    `ID_EMPLEADO` INT NOT NULL,
    `ID_PUESTO` INT,
    `NOMBRE_EMPLEADO` VARCHAR(255) NOT NULL,
    `DNI_EMPLEADO` VARCHAR(20) NOT NULL,
    `FECHA_NACIMIENTO` DATE NOT NULL,
    `CELULAR` VARCHAR(15) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    `CONTACTO_EMERGENCIA` VARCHAR(15) NOT NULL,
    `FECHA_INGRESO` DATE NOT NULL,
    `SALARIO` DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_EMPLEADO),
    FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS_EMPLEADOS(ID_PUESTO)
    );

-- Tabla CLASES
DROP TABLE IF EXISTS CLASES;
CREATE TABLE `CLASES` (
    `ID_CLASE` INT NOT NULL,
    `NOMBRE_CLASE` VARCHAR(255) NOT NULL,
    `ID_EMPLEADO` INT,
    `DIAS` VARCHAR(255) NOT NULL,
    `HORARIO_INICIO` TIME NOT NULL,
    `HORARIO_FIN` TIME NOT NULL,
    `ID_MATERIAL` INT,
    PRIMARY KEY (ID_CLASE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALES(ID_MATERIAL)
);


-- Tabla PAGOS_EMPLEADOS
DROP TABLE IF EXISTS PAGOS_EMPLEADOS;
CREATE TABLE `PAGOS_EMPLEADOS` (
    `ID_EMPLEADO` INT,
	`DNI_EMPLEADO` VARCHAR(255) NOT NULL,
    `CBU` VARCHAR(255) NOT NULL,
    `ALIAS` VARCHAR(255) NOT NULL,
    `BANCO` VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_EMPLEADO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

-- Tabla de log para MIEMBROS
CREATE TABLE MIEMBROS_LOG (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    OPERACION VARCHAR(10) NOT NULL,
    ID_MIEMBRO INT,
    NOMBRE_MIEMBRO VARCHAR(255),
    DNI_MIEMBRO INT,
    FECHA_OPERACION DATETIME,
    USUARIO_OPERACION VARCHAR(255)
);

-- Tabla de log para PAGOS
CREATE TABLE PAGOS_LOG (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    OPERACION VARCHAR(10) NOT NULL,
    ID_MIEMBRO INT,
    TIPO_MEMBRESIA VARCHAR(255),
    MONTO DECIMAL(10, 2),
    FECHA_ULTIMO_PAGO DATE,
    METODO_DE_PAGO VARCHAR(255),
    FECHA_OPERACION DATETIME,
    USUARIO_OPERACION VARCHAR(255)
);